stages:
- test

sast:
  stage: test
include:
- template: Security/SAST.gitlab-ci.yml

check-cards-job:
  stage: test
  image: node:22-alpine
  script:
    - cp v4.json v4.json.bak
    - npm run update-cards
    - diff -u v4.json v4.json.bak
